// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRU5guGqrccX9VW0aplIgPd_NidQYGNK4',
    appId: '1:439428576170:web:444ece142a21e4ddc1f1d3',
    messagingSenderId: '439428576170',
    projectId: 'flutter-app-test-df339',
    authDomain: 'flutter-app-test-df339.firebaseapp.com',
    storageBucket: 'flutter-app-test-df339.appspot.com',
    measurementId: 'G-N25MM98S15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZROr9q7IAIyLHOErzsxkWEZvQp-Ywpb0',
    appId: '1:439428576170:android:1ddb3959ee716749c1f1d3',
    messagingSenderId: '439428576170',
    projectId: 'flutter-app-test-df339',
    storageBucket: 'flutter-app-test-df339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfvmyUU_pBvZiXGDqriJPlOObXqoJKWfU',
    appId: '1:439428576170:ios:112614eb15ad3205c1f1d3',
    messagingSenderId: '439428576170',
    projectId: 'flutter-app-test-df339',
    storageBucket: 'flutter-app-test-df339.appspot.com',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfvmyUU_pBvZiXGDqriJPlOObXqoJKWfU',
    appId: '1:439428576170:ios:800932f9e62be390c1f1d3',
    messagingSenderId: '439428576170',
    projectId: 'flutter-app-test-df339',
    storageBucket: 'flutter-app-test-df339.appspot.com',
    iosBundleId: 'com.example.calendar.RunnerTests',
  );
}
